apiVersion: v1
kind: Namespace
metadata:
  name: chatbot-ui
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui
  namespace: chatbot-ui
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    name: http
    targetPort: http
  selector:
    app: chatbot-ui
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui
  namespace: chatbot-ui
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      name: http
      targetPort: http
  selector:
    app: chatbot-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
  namespace: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
        - name: chatbot-ui
          image: docker.io/labring4docker/chatbot-ui:main
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            protocol: TCP
            containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
