apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-zot-hook"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-zot-hook"
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: zot-hook
          image: busybox:latest
          command: ["sh", "-c", "until echo exit | telnet {{.Values.zot.host}} {{.Values.zot.port}}; do echo waiting for zot; sleep 5; done;"]
