apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
      s3: {{ toJson .Values.s3  }}
      delete:
        enabled: {{ .Values.deleteEnable }}
    http:
      addr: :5000
      debug:
        addr: :5001
        prometheus:
          enabled: {{.Values.prometheusEnable}}
          path: /metrics
      headers:
        X-Content-Type-Options: [nosniff]
      {{- if .Values.tlsEnable }}
      tls:
        certificate: /tmp/serving-certs/tls.crt
        key: /tmp/serving-certs/tls.key
        clientcas:
        - /tmp/serving-certs/ca.crt
      {{- end }}
    proxy:
      on: true
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    auth:
      htpasswd:
        realm: "Registry Realm"
        path: /etc/docker/registry/htpasswd
