apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: registry
              containerPort: 5000
              protocol: TCP
            - name: debug
              containerPort: 5001
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/serving-certs
              name: cert
              readOnly: true
            - mountPath: '/etc/docker/registry/htpasswd'
              name: {{ .Release.Name }}-secret
              subPath: htpasswd
            - mountPath: '/etc/docker/registry/config.yml'
              name: {{ .Release.Name }}-config
              subPath: config.yml
            {{- if .Values.pvc.create }}
            - mountPath: '/var/lib/registry'
              name: {{ .Release.Name }}-volume
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 5000
            httpGet:
              path: /v2/
              port: 5000
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: Basic {{ printf "%s:%s" .Values.authHeaderUser .Values.authHeaderPassword | b64enc }}
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: Basic {{ printf "%s:%s" .Values.authHeaderUser .Values.authHeaderPassword | b64enc }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{.Values.tlsSecretName}}
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-config
        - name: {{ .Release.Name }}-secret
          secret:
            secretName: {{ .Release.Name }}-secret
        {{- if .Values.pvc.create }}
        - name: {{ .Release.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name | default (printf "%s-pvc" .Release.Name) }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
