{{- if .Values.tlsEnable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
      {{- include "registry.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "registry.fullname" . }}.{{.Release.Namespace}}.svc
    - {{ include "registry.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local
    {{- range .Values.extraDNSNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    kind: Issuer
    name: registry-selfsigned-issuer
  secretName: {{.Values.tlsSecretName}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: registry-selfsigned-issuer
  labels:
      {{- include "registry.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
