accessControl: {
  "**": {
    "policies": [ {
      "users": [ "user" ],
      "actions": [ "read" ]
    } ],
    "defaultPolicy": [ ],
    "anonymousPolicy":["read"]
  },
  "adminPolicy": {
    "users": [ "admin" ],
    "actions": [ "read", "create", "update", "delete" ]
  }
}
